package com.minimart.identity.infrastructure.security

import jakarta.annotation.PostConstruct
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import java.io.File
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.PrivateKey
import java.security.PublicKey
import java.security.interfaces.RSAPrivateCrtKey
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.RSAPublicKeySpec
import java.util.Base64

/**
 * Owns the RSA keypair identity-service uses to sign login JWTs (RS256), per
 * ARCHITECTURE.md §4/§7: "identity-service holds an RSA keypair... The
 * private key never leaves identity-service."
 *
 * ============================================================================
 * DEV/DEMO ONLY — NOT PRODUCTION KEY MANAGEMENT.
 * ============================================================================
 * This component generates a brand-new RSA keypair on first startup and
 * persists the private key, unencrypted, to a local PEM file so restarts
 * don't invalidate every previously issued token or force the (separate)
 * Kong gateway work item to re-read a changed public key. That is adequate
 * for a local/demo phase and nothing more. A production deployment must
 * instead inject the private key from a secret store / KMS (e.g. Vault, AWS
 * KMS/Secrets Manager) as a mounted secret or environment-provided material
 * that this process never generates itself — generating signing keys at
 * application startup and writing them to a plain file is exactly the kind
 * of thing that must not happen once real credentials are on the line.
 * ============================================================================
 *
 * On every startup, the derived public key is (re)written in X.509
 * SubjectPublicKeyInfo PEM form to [JwtProperties.publicKeyExportPath] —
 * fixed at `gateway/keys/identity-dev-public-key.pem` — so Kong's JWT plugin
 * has a stable, current key to verify against.
 */
@Component
final class RsaKeyPairProvider(
    private val jwtProperties: JwtProperties,
) {

    private val logger = LoggerFactory.getLogger(RsaKeyPairProvider::class.java)

    lateinit var privateKey: PrivateKey
        private set

    lateinit var publicKey: PublicKey
        private set

    @PostConstruct
    fun initializeKeyPair() {
        val privateKeyFile = File(jwtProperties.privateKeyPath)

        privateKey = if (privateKeyFile.exists()) {
            logger.info("Loading existing RSA signing key from {}", privateKeyFile.absolutePath)
            readPrivateKey(privateKeyFile)
        } else {
            logger.warn(
                "No RSA signing key found at {}. Generating a new {}-bit dev keypair. " +
                    "This is a dev/demo-only mechanism — see RsaKeyPairProvider's class-level " +
                    "kdoc for why this must not be how a production deployment manages keys.",
                privateKeyFile.absolutePath,
                jwtProperties.keySize,
            )
            val generator = KeyPairGenerator.getInstance(RSA_ALGORITHM)
            generator.initialize(jwtProperties.keySize)
            val generatedKeyPair = generator.generateKeyPair()
            writePrivateKey(privateKeyFile, generatedKeyPair.private)
            generatedKeyPair.private
        }

        publicKey = derivePublicKey(privateKey)

        val publicKeyFile = File(jwtProperties.publicKeyExportPath)
        writePublicKey(publicKeyFile, publicKey)
        logger.info(
            "RSA public key exported to {} for the Kong gateway's JWT plugin to verify against",
            publicKeyFile.absolutePath,
        )
    }

    /**
     * An RSA private key generated (or PKCS8-parsed) via the standard "RSA"
     * KeyFactory is an [RSAPrivateCrtKey], which carries the modulus and
     * public exponent alongside the private exponent — enough to
     * mathematically reconstruct the matching public key without needing to
     * separately persist it. This is standard JCA behavior, not
     * implementation-specific guesswork: PKCS8 RSA private keys generated by
     * `KeyPairGenerator` always include the CRT parameters.
     */
    private fun derivePublicKey(privateKey: PrivateKey): PublicKey {
        check(privateKey is RSAPrivateCrtKey) {
            "Loaded RSA private key does not expose CRT parameters (modulus/public exponent); " +
                "cannot derive the matching public key from it."
        }
        val publicKeySpec = RSAPublicKeySpec(privateKey.modulus, privateKey.publicExponent)
        return KeyFactory.getInstance(RSA_ALGORITHM).generatePublic(publicKeySpec)
    }

    private fun readPrivateKey(file: File): PrivateKey {
        val keyBytes = decodePem(file.readText())
        val keySpec = PKCS8EncodedKeySpec(keyBytes)
        return KeyFactory.getInstance(RSA_ALGORITHM).generatePrivate(keySpec)
    }

    private fun writePrivateKey(file: File, key: PrivateKey) {
        file.parentFile?.mkdirs()
        file.writeText(encodeAsPem("PRIVATE KEY", key.encoded))
    }

    private fun writePublicKey(file: File, key: PublicKey) {
        file.parentFile?.mkdirs()
        file.writeText(encodeAsPem("PUBLIC KEY", key.encoded))
    }

    private fun decodePem(pem: String): ByteArray {
        val base64Body = pem
            .lineSequence()
            .filterNot { it.startsWith("-----") }
            .joinToString("")
        return Base64.getDecoder().decode(base64Body)
    }

    private fun encodeAsPem(label: String, derBytes: ByteArray): String {
        val base64 = Base64.getEncoder().encodeToString(derBytes)
        return buildString {
            append("-----BEGIN ").append(label).append("-----\n")
            base64.chunked(PEM_LINE_LENGTH).forEach { line -> append(line).append('\n') }
            append("-----END ").append(label).append("-----\n")
        }
    }

    private companion object {
        const val RSA_ALGORITHM = "RSA"
        const val PEM_LINE_LENGTH = 64
    }
}
