#!/usr/bin/env bash
# Structural documentation audit for Archive/. See Archive/GOVERNANCE.md §5.
#
# Usage:
#   scripts/doc-audit.sh --check   # run the structural checks, exit 1 if any fail
#   scripts/doc-audit.sh --index   # (re)generate Archive/INDEX.md and Archive/RULE-INDEX.md
#   scripts/doc-audit.sh           # both of the above
#
# Deliberately dependency-light (POSIX shell + grep/find/sort/paste only) — no
# new toolchain, per the lesson already recorded in Archive/Issues/Shell about
# keeping repo scripts simple and their assumptions explicit.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:---all}"
REPORT="$(mktemp)"
trap 'rm -f "$REPORT"' EXIT

fail() { echo "FAIL: $*" | tee -a "$REPORT" >&2; }
warn() { echo "WARN: $*"; }

# Files/paths excluded from checks: _Templates (placeholder text, not real
# docs), Prompts/ (immutable transcripts — see GOVERNANCE.md §2), and the
# generated index files themselves.
EXCLUDE_ARGS=(-not -path 'Archive/_Templates/*' -not -path 'Archive/Prompts/*' -not -name 'INDEX.md' -not -name 'RULE-INDEX.md')

check_broken_paths() {
  echo "== 1. Broken Archive/ path references (excluding _Templates/, Prompts/) =="
  find Archive -type f "${EXCLUDE_ARGS[@]}" -print0 |
  while IFS= read -r -d '' file; do
    grep -noE 'Archive/[A-Za-z0-9_./-]+' "$file" 2>/dev/null | while IFS=: read -r line ref; do
      clean="${ref%.}"
      clean="${clean%,}"
      if [ ! -e "$clean" ]; then
        fail "$file:$line references '$clean' (no such path)"
      fi
    done
  done
}

check_changerequest_pairing() {
  echo "== 2. ChangeRequest without a matching ChangeLog/Implementation entry =="
  find Archive -type f -path '*/ChangeRequest/Request-*' -print0 |
  while IFS= read -r -d '' cr; do
    reqname="$(basename "$cr")"
    section_dir="$(dirname "$(dirname "$cr")")"
    match="$(find "$section_dir" -type f \( -path '*/ChangeLog/*' -o -path '*/Implementation/*' \) -name "$reqname" 2>/dev/null | head -1)"
    if [ -z "$match" ]; then
      fail "$cr has no matching ChangeLog/Implementation entry under $section_dir"
    fi
  done
}

check_headers() {
  echo "== 3. Required header block (warn-only — see GOVERNANCE.md §3) =="
  local targets=(
    Archive/Architecture/ARCHITECTURE.md
    Archive/Architecture/Discussion.md
    Archive/BusinessRules/BUSINESS_RULES.md
    Archive/Development/Database
    Archive/GOVERNANCE.md
  )
  for f in "${targets[@]}"; do
    [ -f "$f" ] || continue
    if ! grep -q '\*\*Status:\*\*' "$f"; then
      warn "$f has no Status/Owner role/Date header block"
    fi
  done
}

generate_index() {
  local idx="Archive/INDEX.md"
  {
    echo "# Archive Index"
    echo
    echo "Generated by \`scripts/doc-audit.sh --index\` — do not hand-edit, re-run the script instead."
    echo
    echo "| Doc | Status | Owner role | Date | Depends on |"
    echo "|---|---|---|---|---|"
    find Archive -type f "${EXCLUDE_ARGS[@]}" | sort |
    while read -r f; do
      status="$(grep -m1 -oE '\*\*Status:\*\*.*' "$f" 2>/dev/null | sed -E 's/\*\*Status:\*\* *//')"
      owner="$(grep -m1 -oE '\*\*Owner role:\*\*.*' "$f" 2>/dev/null | sed -E 's/\*\*Owner role:\*\* *//')"
      date="$(grep -m1 -oE '\*\*Date:\*\*.*' "$f" 2>/dev/null | sed -E 's/\*\*Date:\*\* *//')"
      depends="$(grep -m1 -oE '\*\*Depends on:\*\*.*' "$f" 2>/dev/null | sed -E 's/\*\*Depends on:\*\* *//')"
      echo "| \`$f\` | ${status:-—} | ${owner:-—} | ${date:-—} | ${depends:-—} |"
    done
  } > "$idx"
  echo "Wrote $idx"
}

generate_rule_index() {
  local idx="Archive/RULE-INDEX.md"
  local ids
  ids="$(grep -rhoE '\b(ACC|CAT|ORD|NTF|GEN)-[0-9]{3}\b' Archive --exclude-dir=_Templates 2>/dev/null | sort -u)"
  {
    echo "# Rule-ID Cross-Reference"
    echo
    echo "Generated by \`scripts/doc-audit.sh --index\` — do not hand-edit, re-run the script instead."
    echo
    echo "| Rule ID | Referenced in |"
    echo "|---|---|"
    for id in $ids; do
      files="$(grep -rl "\b$id\b" Archive --exclude-dir=_Templates --exclude=RULE-INDEX.md --exclude=INDEX.md 2>/dev/null | sort | paste -sd, -)"
      echo "| $id | $files |"
    done
  } > "$idx"
  echo "Wrote $idx"
}

run_check() {
  check_broken_paths
  check_changerequest_pairing
  check_headers
  echo
  if [ -s "$REPORT" ]; then
    echo "doc-audit: $(wc -l < "$REPORT" | tr -d ' ') failing check(s):"
    cat "$REPORT"
    return 1
  fi
  echo "doc-audit: all structural checks passed."
  return 0
}

run_index() {
  generate_index
  generate_rule_index
}

case "$MODE" in
  --check) run_check ;;
  --index) run_index ;;
  --all)   run_index; run_check ;;
  *) echo "Usage: $0 [--check|--index]" >&2; exit 2 ;;
esac
